apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: tyyikz69b-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/rhtap-qe:db03ddcc0119424139c74b7f83e854bf73db6517@sha256:e17e683de03ec6745958d48d3696d22578e6d7a8ada9442b2da02f1afef23050
        name: container-image  
