apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tyyikz69b-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/tyyikz69b-java-quarkus